feign:
  hystrix.enabled: true

# To set thread isolation to SEMAPHORE
hystrix.command.default.execution.isolation.strategy: SEMAPHORE

logging.level.covid19api.facade.api:
  client.CovidApiClient: INFO
